spring:
  datasource:
    username: root
    password: ghehas2008
    url: "jdbc:mysql://localhost:3306/adoptions"

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl: update
